name: fms
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  path_provider: ^2.1.5
  fl_chart: 0.71.0
  flutter:
    sdk: flutter
  intl: 0.20.2


  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0           # For Figma-style fonts
  flutter_svg: ^2.0.7            # For using SVG icons from Figma
  # Uncomment if you use navigation or state mgmt:
  # provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
#    - assets/icons/
#    - assets/images/

#  fonts:
#    - family: Urbanist
#      fonts:
#        - asset: assets/fonts/Urbanist-Regular.ttf
#        - asset: assets/fonts/Urbanist-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Urbanist-SemiBold.ttf
#          weight: 600
